### ISSUE TITLE
undefined symbol: running_trap

### ISSUE THREAD

**Issue by junghans** [lanl/MPI-Bash#1]
When running whatever command inside mpibash, I get the following warning:

```
ls: symbol lookup error: /usr/libexec/mpibash/mpibash.so: undefined symbol: running_trap
```

It seems `running_trap` using in `src/init.c` is an `extern int`. The bash source code defines it in `trap.c`, but bash doesn't install a shared object, where the symbol could looked up. Also none of the examples in `examples/loadables` actually use `running_trap`.

**Comment by spakin** [comment]
As I haven't encountered that error myself and the issue is now over two years old, I'm going to mark the issue closed.  Please feel free to re-open the issue if the `running_trap` error reappears.

― Scott
