### ISSUE TITLE
MPI-Bash does not work with bash < 4.4

### ISSUE THREAD

**Issue by jrandall** [lanl/MPI-Bash#10]
Attempting to use MPI-Bash with bash 4.2.x results in an error like: 

```
bash: symbol lookup error: /software/hgi/pkglocal/mpibash-1.3-bash-4.2.53-openmpi-1.10.0-lsf-9.1.1.1/libexec/mpibash/mpibash.so: undefined symbol: find_shell_variable
```
It appears to me that the `find_shell_variable` function was not present in bash 4.2 but rather was added in 4.4. 

If this is true, the installation instructions should probably be updated to state that MPI-Bash only works with bash versions 4.4 and higher.

**Comment by spakin** [comment]
I see `find_shell_variable` in 4.3:
```Bash
$ find bash-4.2 -name "*.c" | xargs grep find_shell_variable
$ find bash-4.3 -name "*.c" | xargs grep find_shell_variable
bash-4.3/variables.c:find_shell_variable (name)
bash-4.3/arrayfunc.c:  entry = find_shell_variable (name);
```

I'll soon update [`INSTALL.md`](/lanl/MPI-Bash/blob/master/INSTALL.md) to indicate that v4.3+ is required for installation.

Thanks for opening the issue,
— Scott
