### ISSUE TITLE
Update Ubuntu guide

### ISSUE THREAD

**Issue by junghans** [lanl/MPI-Bash#9]
I think the `bash-builtins` package on Debian/Ubuntu provids all the headers needed to build mpibash.

**Comment by junghans** [comment]
On a related note, OpenSuse has mpibash: https://build.opensuse.org/package/show/openSUSE:Factory/mpibash

**Comment by junghans** [comment]
And Fedora will soon too: https://bugzilla.redhat.com/show_bug.cgi?id=1513582

**Comment by spakin** [comment]
The [MPI-Bash installation instructions](https://github.com/lanl/MPI-Bash/blob/master/INSTALL.md) now mention

1. the existence of the `mpibash` package on some distributions, and
2. the possibility of installing the `bash-builtins` package as an alternative to pulling down the Bash source code.

**Comment by junghans** [comment]
Fedora (f28 and above) is done: https://koji.fedoraproject.org/koji/taskinfo?taskID=23549041

I also added https://release-monitoring.org/project/16639/ to have a list of all distributions coming with mpibash.
